# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ai_service.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x61i_service.proto\x12\nai_service\"\x9e\x01\n\x0b\x43hatRequest\x12\r\n\x05model\x18\x01 \x01(\t\x12\x0e\n\x06prompt\x18\x02 \x01(\t\x12$\n\x07history\x18\x03 \x03(\x0b\x32\x13.ai_service.Message\x12\x10\n\x08provider\x18\x04 \x01(\t\x12\x0f\n\x07\x61pi_key\x18\x05 \x01(\t\x12\x13\n\x0btemperature\x18\x06 \x01(\x02\x12\x12\n\nmax_tokens\x18\x07 \x01(\x05\"(\n\x07Message\x12\x0c\n\x04role\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\"C\n\x0c\x43hatResponse\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\t\x12\x13\n\x0btokens_used\x18\x02 \x01(\x05\x12\r\n\x05model\x18\x03 \x01(\t\",\n\rTokenResponse\x12\r\n\x05token\x18\x01 \x01(\t\x12\x0c\n\x04\x64one\x18\x02 \x01(\x08\"I\n\x12\x46\x65tchModelsRequest\x12\x10\n\x08provider\x18\x01 \x01(\t\x12\x0f\n\x07\x61pi_key\x18\x02 \x01(\t\x12\x10\n\x08\x62\x61se_url\x18\x03 \x01(\t\"4\n\x13\x46\x65tchModelsResponse\x12\x0e\n\x06models\x18\x01 \x03(\t\x12\r\n\x05\x65rror\x18\x02 \x01(\t\"\x0f\n\rHealthRequest\"1\n\x0eHealthResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0f\n\x07version\x18\x02 \x01(\t2\x9b\x02\n\tAIService\x12\x39\n\x04\x43hat\x12\x17.ai_service.ChatRequest\x1a\x18.ai_service.ChatResponse\x12\x42\n\nStreamChat\x12\x17.ai_service.ChatRequest\x1a\x19.ai_service.TokenResponse0\x01\x12N\n\x0b\x46\x65tchModels\x12\x1e.ai_service.FetchModelsRequest\x1a\x1f.ai_service.FetchModelsResponse\x12?\n\x06Health\x12\x19.ai_service.HealthRequest\x1a\x1a.ai_service.HealthResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ai_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CHATREQUEST']._serialized_start=33
  _globals['_CHATREQUEST']._serialized_end=191
  _globals['_MESSAGE']._serialized_start=193
  _globals['_MESSAGE']._serialized_end=233
  _globals['_CHATRESPONSE']._serialized_start=235
  _globals['_CHATRESPONSE']._serialized_end=302
  _globals['_TOKENRESPONSE']._serialized_start=304
  _globals['_TOKENRESPONSE']._serialized_end=348
  _globals['_FETCHMODELSREQUEST']._serialized_start=350
  _globals['_FETCHMODELSREQUEST']._serialized_end=423
  _globals['_FETCHMODELSRESPONSE']._serialized_start=425
  _globals['_FETCHMODELSRESPONSE']._serialized_end=477
  _globals['_HEALTHREQUEST']._serialized_start=479
  _globals['_HEALTHREQUEST']._serialized_end=494
  _globals['_HEALTHRESPONSE']._serialized_start=496
  _globals['_HEALTHRESPONSE']._serialized_end=545
  _globals['_AISERVICE']._serialized_start=548
  _globals['_AISERVICE']._serialized_end=831
# @@protoc_insertion_point(module_scope)
